title: /var/log/seiji
name: Seiji Toyama
email: seijit@me.com
url: http://blog.seiji.me
permalink: /:year/:month/:day/:title
markdown: rdiscount
safe: false
lsi: false
pygments: true
include: ['_config']
exclude: ['Capfile', 'Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile', 'bower.json', 'config', 'misc']
paginate: 5
