name: \x6d\x65\x6d\x6f\x6e
author:
  name: Seiji Toyama
  email: seijit@me.com
permalink: /:year/:month/:day/:title
markdown: rdiscount
safe: false
lsi: false
pygments: true
exclude: ['Capfile', 'Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile', 'bower.json', 'config', 'misc']
paginate: 5
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  compress:
    js:   ~
    css:  ~