title: /var/log/seiji
name: Seiji Toyama
email: seijit@me.com
url: http://blog.seiji.me
permalink: /:year/:month/:day/:title
markdown: rdiscount
safe: false
lsi: false
pygments: true
include: []
exclude: [
  'Capfile',
  'Dockerfile',
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'Rakefile',
  '_config',
  'bower.json',
  'circle.yml',
  'config',
  'fig.yml',
  'misc']
paginate: 5
