name: \x6d\x65\x6d\x6f\x6e
author:
  name: Seiji Toyama
  email: seijit@me.com
url: blog.seiji.me
permalink: /:year/:month/:day/:title
markdown: rdiscount
safe: false
lsi: false
pygments: true
include: ['_config']
exclude: ['Capfile', 'Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile', 'bower.json', 'config', 'misc']
paginate: 5
